version: '3'
services:
### 網頁伺服器的container ##################################
 web:
  image: gogs/gogs
  dns: 8.8.8.8
  ports:
    # 使用隨機的port 80
    - "10080:3000"
    - "10022:22"
  volumes:
    - ./git:/data/git
    - ./etc/app.ini:/data/gogs/conf/app.ini
  hostname: gogs
  networks:
    - dlaravel_net
  
### 資料庫 container ##################################
 db:
  image: mysql:5.7
  network_mode: "service:web"
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
  volumes:
    - ./data:/var/lib/mysql
    - ./etc/mysql/conf.d:/etc/mysql/conf.d
  environment:
   - MYSQL_DATABASE=gogs
   - MYSQL_USER=gogs
   - MYSQL_PASSWORD=gogs
   - MYSQL_ROOT_PASSWORD=123456
   # - MYSQL_ALLOW_EMPTY_PASSWORD= "yes"
   - TZ=Asia/Taipei

######top-level netowks key#######
networks:
    dlaravel_net: